/**
 * Canonical Amount request contract shared by the Floreat frontend and backend.
 * An Amount holds the cost summary fields for a job as a flat model.
 */
import { z } from 'zod'

const num = z.number().nullish()

export const createAmountSchema = z.object({
  steelStructuresQuantity: num,
  steelStructuresFabricationRate: num,
  steelStructuresErrectionRate: num,
  steelStructuresLoadingRate: num,
  steelStructuresFabricationAmount: num,
  steelStructuresErrectionAmount: num,
  steelStructuresLoadingAmount: num,

  windBracingsQuantity: num,
  windBracingsFabricationRate: num,
  windBracingsErrectionRate: num,
  windBracingsLoadingRate: num,
  windBracingsFabricationAmount: num,
  windBracingsErrectionAmount: num,
  windBracingsLoadingAmount: num,

  sagRodQuantity: num,
  sagRodFabricationRate: num,
  sagRodErrectionRate: num,
  sagRodLoadingRate: num,
  sagRodFabricationAmount: num,
  sagRodErrectionAmount: num,
  sagRodLoadingAmount: num,

  flangeBraceQuantity: num,
  flangeBraceFabricationRate: num,
  flangeBraceErrectionRate: num,
  flangeBraceLoadingRate: num,
  flangeBraceFabricationAmount: num,
  flangeBraceErrectionAmount: num,
  flangeBraceLoadingAmount: num,

  zCPurlinsQuantity: num,
  zCPurlinsFabricationRate: num,
  zCPurlinsErrectionRate: num,
  zCPurlinsLoadingRate: num,
  zCPurlinsFabricationAmount: num,
  zCPurlinsErrectionAmount: num,
  zCPurlinsLoadingAmount: num,

  roofSheetQuantity: num,
  roofSheetFabricationRate: num,
  roofSheetErrectionRate: num,
  roofSheetLoadingRate: num,
  roofSheetFabricationAmount: num,
  roofSheetErrectionAmount: num,
  roofSheetLoadingAmount: num,

  claddingSheetQuantity: num,
  claddingSheetFabricationRate: num,
  claddingSheetErrectionRate: num,
  claddingSheetLoadingRate: num,
  claddingSheetFabricationAmount: num,
  claddingSheetErrectionAmount: num,
  claddingSheetLoadingAmount: num,

  canopySheetQuantity: num,
  canopySheetFabricationRate: num,
  canopySheetErrectionRate: num,
  canopySheetLoadingRate: num,
  canopySheetFabricationAmount: num,
  canopySheetErrectionAmount: num,
  canopySheetLoadingAmount: num,

  purlinBoltsQuantity: num,
  purlinBoltsFabricationRate: num,
  purlinBoltsErrectionRate: num,
  purlinBoltsLoadingRate: num,
  purlinBoltsFabricationAmount: num,
  purlinBoltsErrectionAmount: num,
  purlinBoltsLoadingAmount: num,

  jointBoltsQuantity: num,
  jointBoltsFabricationRate: num,
  jointBoltsErrectionRate: num,
  jointBoltsLoadingRate: num,
  jointBoltsFabricationAmount: num,
  jointBoltsErrectionAmount: num,
  jointBoltsLoadingAmount: num,

  foundationBoltsQuantity: num,
  foundationBoltsFabricationRate: num,
  foundationBoltsErrectionRate: num,
  foundationBoltsLoadingRate: num,
  foundationBoltsFabricationAmount: num,
  foundationBoltsErrectionAmount: num,
  foundationBoltsLoadingAmount: num,

  anchorBoltsQuantity: num,
  anchorBoltsFabricationRate: num,
  anchorBoltsErrectionRate: num,
  anchorBoltsLoadingRate: num,
  anchorBoltsFabricationAmount: num,
  anchorBoltsErrectionAmount: num,
  anchorBoltsLoadingAmount: num,

  ridgeQuantity: num,
  ridgeFabricationRate: num,
  ridgeErrectionRate: num,
  ridgeLoadingRate: num,
  ridgeFabricationAmount: num,
  ridgeErrectionAmount: num,
  ridgeLoadingAmount: num,

  gutterQuantity: num,
  gutterFabricationRate: num,
  gutterErrectionRate: num,
  gutterLoadingRate: num,
  gutterFabricationAmount: num,
  gutterErrectionAmount: num,
  gutterLoadingAmount: num,

  downtakeQuantity: num,
  downtakeFabricationRate: num,
  downtakeErrectionRate: num,
  downtakeLoadingRate: num,
  downtakeFabricationAmount: num,
  downtakeErrectionAmount: num,
  downtakeLoadingAmount: num,

  dripTrimQuantity: num,
  dripTrimFabricationRate: num,
  dripTrimErrectionRate: num,
  dripTrimLoadingRate: num,
  dripTrimFabricationAmount: num,
  dripTrimErrectionAmount: num,
  dripTrimLoadingAmount: num,

  flashingQuantity: num,
  flashingFabricationRate: num,
  flashingErrectionRate: num,
  flashingLoadingRate: num,
  flashingFabricationAmount: num,
  flashingErrectionAmount: num,
  flashingLoadingAmount: num,

  rollingShutterQuantity: num,
  rollingShutterFabricationRate: num,
  rollingShutterErrectionRate: num,
  rollingShutterLoadingRate: num,
  rollingShutterFabricationAmount: num,
  rollingShutterErrectionAmount: num,
  rollingShutterLoadingAmount: num,

  louversQuantity: num,
  louversFabricationRate: num,
  louversErrectionRate: num,
  louversLoadingRate: num,
  louversFabricationAmount: num,
  louversErrectionAmount: num,
  louversLoadingAmount: num,

  skyLightQuantity: num,
  skyLightFabricationRate: num,
  skyLightErrectionRate: num,
  skyLightLoadingRate: num,
  skyLightFabricationAmount: num,
  skyLightErrectionAmount: num,
  skyLightLoadingAmount: num,

  wallLightQuantity: num,
  wallLightFabricationRate: num,
  wallLightErrectionRate: num,
  wallLightLoadingRate: num,
  wallLightFabricationAmount: num,
  wallLightErrectionAmount: num,
  wallLightLoadingAmount: num,

  roofInsulationQuantity: num,
  roofInsulationFabricationRate: num,
  roofInsulationErrectionRate: num,
  roofInsulationLoadingRate: num,
  roofInsulationFabricationAmount: num,
  roofInsulationErrectionAmount: num,
  roofInsulationLoadingAmount: num,

  wallInsulationQuantity: num,
  wallInsulationFabricationRate: num,
  wallInsulationErrectionRate: num,
  wallInsulationLoadingRate: num,
  wallInsulationFabricationAmount: num,
  wallInsulationErrectionAmount: num,
  wallInsulationLoadingAmount: num,

  turboVentilatorsQuantity: num,
  turboVentilatorsFabricationRate: num,
  turboVentilatorsErrectionRate: num,
  turboVentilatorsLoadingRate: num,
  turboVentilatorsFabricationAmount: num,
  turboVentilatorsErrectionAmount: num,
  turboVentilatorsLoadingAmount: num,

  deckingSheetQuantity: num,
  deckingSheetFabricationRate: num,
  deckingSheetErrectionRate: num,
  deckingSheetLoadingRate: num,
  deckingSheetFabricationAmount: num,
  deckingSheetErrectionAmount: num,
  deckingSheetLoadingAmount: num,

  shearStudsQuantity: num,
  shearStudsFabricationRate: num,
  shearStudsErrectionRate: num,
  shearStudsLoadingRate: num,
  shearStudsFabricationAmount: num,
  shearStudsErrectionAmount: num,
  shearStudsLoadingAmount: num,

  polyCarbonateSheetQuantity: num,
  polyCarbonateSheetFabricationRate: num,
  polyCarbonateSheetErrectionRate: num,
  polyCarbonateSheetLoadingRate: num,
  polyCarbonateSheetFabricationAmount: num,
  polyCarbonateSheetErrectionAmount: num,
  polyCarbonateSheetLoadingAmount: num,

  stair1Quantity: num,
  stair1FabricationRate: num,
  stair1ErrectionRate: num,
  stair1LoadingRate: num,
  stair1FabricationAmount: num,
  stair1ErrectionAmount: num,
  stair1LoadingAmount: num,

  stair2Quantity: num,
  stair2FabricationRate: num,
  stair2ErrectionRate: num,
  stair2LoadingRate: num,
  stair2FabricationAmount: num,
  stair2ErrectionAmount: num,
  stair2LoadingAmount: num,

  handrailQuantity: num,
  handrailFabricationRate: num,
  handrailErrectionRate: num,
  handrailLoadingRate: num,
  handrailFabricationAmount: num,
  handrailErrectionAmount: num,
  handrailLoadingAmount: num,

  canopySideCoveringQuantity: num,
  canopySideCoveringFabricationRate: num,
  canopySideCoveringErrectionRate: num,
  canopySideCoveringLoadingRate: num,
  canopySideCoveringFabricationAmount: num,
  canopySideCoveringErrectionAmount: num,
  canopySideCoveringLoadingAmount: num,

  doorsQuantity: num,
  doorsFabricationRate: num,
  doorsErrectionRate: num,
  doorsLoadingRate: num,
  doorsFabricationAmount: num,
  doorsErrectionAmount: num,
  doorsLoadingAmount: num,

  windowsQuantity: num,
  windowsFabricationRate: num,
  windowsErrectionRate: num,
  windowsLoadingRate: num,
  windowsFabricationAmount: num,
  windowsErrectionAmount: num,
  windowsLoadingAmount: num,

  fasciaStructureQuantity: num,
  fasciaStructureFabricationRate: num,
  fasciaStructureErrectionRate: num,
  fasciaStructureLoadingRate: num,
  fasciaStructureFabricationAmount: num,
  fasciaStructureErrectionAmount: num,
  fasciaStructureLoadingAmount: num,

  fasciaCoveringSheetBoardQuantity: num,
  fasciaCoveringSheetBoardFabricationRate: num,
  fasciaCoveringSheetBoardErrectionRate: num,
  fasciaCoveringSheetBoardLoadingRate: num,
  fasciaCoveringSheetBoardFabricationAmount: num,
  fasciaCoveringSheetBoardErrectionAmount: num,
  fasciaCoveringSheetBoardLoadingAmount: num,

  internalPartitionsQuantity: num,
  internalPartitionsFabricationRate: num,
  internalPartitionsErrectionRate: num,
  internalPartitionsLoadingRate: num,
  internalPartitionsFabricationAmount: num,
  internalPartitionsErrectionAmount: num,
  internalPartitionsLoadingAmount: num,
})

export const updateAmountSchema = createAmountSchema.partial()

export type CreateAmountInput = z.infer<typeof createAmountSchema>
export type UpdateAmountInput = z.infer<typeof updateAmountSchema>

/**
 * The 36 canonical amount line-item descriptions shown in every job's bill of quantities.
 * `rateItem` maps each description to its corresponding Rate master `item` name for rate lookup.
 */
export const DEFAULT_AMOUNT_ITEMS: {
  description: string
  unit: 'KG' | 'RM' | 'SQM' | 'NOS'
  rateItem?: string
}[] = [
  { description: 'STEEL STRUCTURES', unit: 'KG', rateItem: 'STEEL STRUCTURE' },
  { description: 'WIND BRACINGS', unit: 'RM', rateItem: 'WIND BRACING - ROD' },
  { description: 'SAG ROD', unit: 'RM', rateItem: 'SAG ROD - 12 MM' },
  { description: 'FLANGE BRACE', unit: 'KG', rateItem: 'FLANGE BRACE - GI' },
  { description: 'Z/C PURLINS', unit: 'KG', rateItem: 'Z/C - PURLINS' },
  { description: 'ROOF SHEET', unit: 'SQM', rateItem: 'PUFF SHEET 30MM THICK - ROOF' },
  { description: 'CLADDING SHEET', unit: 'SQM', rateItem: 'PPGL 0.4MM THICK - CLADDING' },
  { description: 'CANOPY SHEET', unit: 'SQM', rateItem: 'PPGL 0.4MM THICK - CANOPY' },
  { description: 'PURLIN BOLTS', unit: 'NOS', rateItem: '12 MM DIA BOLT - ORD' },
  { description: 'JOINT BOLTS', unit: 'NOS', rateItem: '16 MM DIA BOLT - HSFG' },
  { description: 'FOUNDATION BOLTS', unit: 'NOS', rateItem: '20 MM FOUNDATION BOLT' },
  { description: 'ANCHOR BOLTS', unit: 'NOS', rateItem: '20 MM ANCHOR BOLT' },
  { description: 'RIDGE', unit: 'RM', rateItem: 'RIDGE' },
  { description: 'GUTTER', unit: 'RM', rateItem: 'GUTTER' },
  { description: 'DOWNTAKE', unit: 'RM', rateItem: 'DOWNTAKE' },
  { description: 'DRIP TRIM', unit: 'RM', rateItem: 'DRIP TRIM' },
  { description: 'FLASHING', unit: 'RM', rateItem: 'FLASHING' },
  { description: 'ROLLING SHUTTER', unit: 'SQM', rateItem: 'ROLLING SHUTTER' },
  { description: 'LOUVERS', unit: 'SQM', rateItem: 'LOUVERS' },
  { description: 'SKY LIGHT', unit: 'SQM', rateItem: 'SKY LIGHT' },
  { description: 'WALL LIGHT', unit: 'SQM', rateItem: 'WALL LIGHT' },
  { description: 'ROOF INSULATION', unit: 'SQM', rateItem: 'INSULATION' },
  { description: 'WALL INSULATION', unit: 'SQM', rateItem: 'INSULATION' },
  { description: 'TURBO VENTILATORS', unit: 'NOS', rateItem: 'TURBO VENTILATORS' },
  { description: 'DECKING SHEET', unit: 'SQM', rateItem: 'DECKING SHEET' },
  { description: 'SHEAR STUDS', unit: 'NOS', rateItem: 'SHEAR STUDS' },
  { description: 'POLY CARBONATE SHEET', unit: 'SQM', rateItem: 'POLYCARBONATE SHEET' },
  { description: 'STAIR - HR SECTION', unit: 'KG', rateItem: 'STAIR - HR SECTION' },
  { description: 'STAIR 6MM CHQ PLATE STEPS', unit: 'KG', rateItem: 'STAIR 6MM CHQ PLATE STEPS' },
  { description: 'HANDRAIL', unit: 'KG', rateItem: 'HANDRAIL' },
  { description: 'CANOPY SIDE COVERING', unit: 'SQM', rateItem: 'CANOPY SIDE COVERING' },
  { description: 'DOORS', unit: 'SQM', rateItem: 'DOORS' },
  { description: 'WINDOWS', unit: 'SQM', rateItem: 'WINDOWS' },
  { description: 'FASCIA STRUCTURE', unit: 'KG', rateItem: 'FASCIA STRUCTURE' },
  { description: 'FASCIA COVERING SHEET/ BOARD', unit: 'SQM', rateItem: 'FASCIA COVERING SHEET / BOARD' },
  { description: 'INTERNAL PARTITIONS', unit: 'SQM', rateItem: 'INTERNAL PARTITIONS' },
]

