ALTER TABLE "Job" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3), ADD COLUMN IF NOT EXISTS "deletedBy" TEXT, ADD COLUMN IF NOT EXISTS "deletionBatchId" TEXT;
ALTER TABLE "Accessories" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3), ADD COLUMN IF NOT EXISTS "deletedBy" TEXT, ADD COLUMN IF NOT EXISTS "deletionBatchId" TEXT;
ALTER TABLE "Amount" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3), ADD COLUMN IF NOT EXISTS "deletedBy" TEXT, ADD COLUMN IF NOT EXISTS "deletionBatchId" TEXT;
ALTER TABLE "Canopy" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3), ADD COLUMN IF NOT EXISTS "deletedBy" TEXT, ADD COLUMN IF NOT EXISTS "deletionBatchId" TEXT;
ALTER TABLE "CanopyItem" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3), ADD COLUMN IF NOT EXISTS "deletedBy" TEXT, ADD COLUMN IF NOT EXISTS "deletionBatchId" TEXT;
ALTER TABLE "Joint" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3), ADD COLUMN IF NOT EXISTS "deletedBy" TEXT, ADD COLUMN IF NOT EXISTS "deletionBatchId" TEXT;
ALTER TABLE "JointBoltRoof" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3), ADD COLUMN IF NOT EXISTS "deletedBy" TEXT, ADD COLUMN IF NOT EXISTS "deletionBatchId" TEXT;
ALTER TABLE "JointBoltMezzanine" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3), ADD COLUMN IF NOT EXISTS "deletedBy" TEXT, ADD COLUMN IF NOT EXISTS "deletionBatchId" TEXT;
ALTER TABLE "FoundationBoltRoof" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3), ADD COLUMN IF NOT EXISTS "deletedBy" TEXT, ADD COLUMN IF NOT EXISTS "deletionBatchId" TEXT;
ALTER TABLE "Load" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3), ADD COLUMN IF NOT EXISTS "deletedBy" TEXT, ADD COLUMN IF NOT EXISTS "deletionBatchId" TEXT;
ALTER TABLE "Mezzanine" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3), ADD COLUMN IF NOT EXISTS "deletedBy" TEXT, ADD COLUMN IF NOT EXISTS "deletionBatchId" TEXT;
ALTER TABLE "MezzanineFloor" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3), ADD COLUMN IF NOT EXISTS "deletedBy" TEXT, ADD COLUMN IF NOT EXISTS "deletionBatchId" TEXT;
ALTER TABLE "MezzanineFloorExtension" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3), ADD COLUMN IF NOT EXISTS "deletedBy" TEXT, ADD COLUMN IF NOT EXISTS "deletionBatchId" TEXT;
ALTER TABLE "Quantity" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3), ADD COLUMN IF NOT EXISTS "deletedBy" TEXT, ADD COLUMN IF NOT EXISTS "deletionBatchId" TEXT;
ALTER TABLE "QuantityPebRoof" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3), ADD COLUMN IF NOT EXISTS "deletedBy" TEXT, ADD COLUMN IF NOT EXISTS "deletionBatchId" TEXT;
ALTER TABLE "QuantityCladding" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3), ADD COLUMN IF NOT EXISTS "deletedBy" TEXT, ADD COLUMN IF NOT EXISTS "deletionBatchId" TEXT;
ALTER TABLE "QuantityCanopy" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3), ADD COLUMN IF NOT EXISTS "deletedBy" TEXT, ADD COLUMN IF NOT EXISTS "deletionBatchId" TEXT;
ALTER TABLE "QuantityAccessories" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3), ADD COLUMN IF NOT EXISTS "deletedBy" TEXT, ADD COLUMN IF NOT EXISTS "deletionBatchId" TEXT;
ALTER TABLE "QuantityMezzanine" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3), ADD COLUMN IF NOT EXISTS "deletedBy" TEXT, ADD COLUMN IF NOT EXISTS "deletionBatchId" TEXT;
ALTER TABLE "QuantityStair" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3), ADD COLUMN IF NOT EXISTS "deletedBy" TEXT, ADD COLUMN IF NOT EXISTS "deletionBatchId" TEXT;
ALTER TABLE "QuantityAdditionalBolts" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3), ADD COLUMN IF NOT EXISTS "deletedBy" TEXT, ADD COLUMN IF NOT EXISTS "deletionBatchId" TEXT;
ALTER TABLE "Quotation" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3), ADD COLUMN IF NOT EXISTS "deletedBy" TEXT, ADD COLUMN IF NOT EXISTS "deletionBatchId" TEXT;
ALTER TABLE "Rate" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3), ADD COLUMN IF NOT EXISTS "deletedBy" TEXT, ADD COLUMN IF NOT EXISTS "deletionBatchId" TEXT;
ALTER TABLE "Roof" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3), ADD COLUMN IF NOT EXISTS "deletedBy" TEXT, ADD COLUMN IF NOT EXISTS "deletionBatchId" TEXT;
ALTER TABLE "Sidewall" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3), ADD COLUMN IF NOT EXISTS "deletedBy" TEXT, ADD COLUMN IF NOT EXISTS "deletionBatchId" TEXT;
ALTER TABLE "Spec" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3), ADD COLUMN IF NOT EXISTS "deletedBy" TEXT, ADD COLUMN IF NOT EXISTS "deletionBatchId" TEXT;
ALTER TABLE "SpecProduct" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3), ADD COLUMN IF NOT EXISTS "deletedBy" TEXT, ADD COLUMN IF NOT EXISTS "deletionBatchId" TEXT;
ALTER TABLE "Stair" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3), ADD COLUMN IF NOT EXISTS "deletedBy" TEXT, ADD COLUMN IF NOT EXISTS "deletionBatchId" TEXT;
ALTER TABLE "StairItem" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3), ADD COLUMN IF NOT EXISTS "deletedBy" TEXT, ADD COLUMN IF NOT EXISTS "deletionBatchId" TEXT;
ALTER TABLE "AreaDeduction" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3), ADD COLUMN IF NOT EXISTS "deletedBy" TEXT, ADD COLUMN IF NOT EXISTS "deletionBatchId" TEXT;
CREATE INDEX IF NOT EXISTS "Job_deletedAt_idx" ON "Job"("deletedAt");
CREATE INDEX IF NOT EXISTS "Rate_jobId_deletedAt_idx" ON "Rate"("jobId", "deletedAt");

-- Replace full unique constraints with active-row-only unique indexes. Prisma
-- still retains the unique selectors in the schema/client, while PostgreSQL
-- permits historical soft-deleted rows to coexist with a new active row.
DROP INDEX IF EXISTS "Accessories_jobId_key";
DROP INDEX IF EXISTS "Amount_jobId_key";
DROP INDEX IF EXISTS "Canopy_jobId_key";
DROP INDEX IF EXISTS "Joint_jobId_key";
DROP INDEX IF EXISTS "Load_jobId_key";
DROP INDEX IF EXISTS "Mezzanine_jobId_key";
DROP INDEX IF EXISTS "Quantity_jobId_key";
DROP INDEX IF EXISTS "Quotation_jobId_key";
DROP INDEX IF EXISTS "Roof_jobId_key";
DROP INDEX IF EXISTS "Spec_jobId_key";
DROP INDEX IF EXISTS "Stair_jobId_key";
DROP INDEX IF EXISTS "QuantityPebRoof_quantityId_key";
DROP INDEX IF EXISTS "QuantityCladding_quantityId_key";
DROP INDEX IF EXISTS "QuantityCanopy_quantityId_key";
DROP INDEX IF EXISTS "QuantityAccessories_quantityId_key";
DROP INDEX IF EXISTS "QuantityMezzanine_quantityId_key";
DROP INDEX IF EXISTS "QuantityStair_quantityId_key";
DROP INDEX IF EXISTS "QuantityAdditionalBolts_quantityId_key";
DROP INDEX IF EXISTS "Rate_jobId_item_key";
DROP INDEX IF EXISTS "CanopyItem_canopyId_code_key";
DROP INDEX IF EXISTS "JointBoltRoof_jointId_roofJointId_key";
DROP INDEX IF EXISTS "JointBoltMezzanine_jointId_mezzanineJointId_key";
DROP INDEX IF EXISTS "FoundationBoltRoof_jointId_foundationJointId_key";
DROP INDEX IF EXISTS "MezzanineFloor_mezzanineId_code_key";
DROP INDEX IF EXISTS "MezzanineFloorExtension_mezzanineId_code_key";
DROP INDEX IF EXISTS "Sidewall_roofId_side_key";
DROP INDEX IF EXISTS "SpecProduct_specId_code_key";
DROP INDEX IF EXISTS "StairItem_stairId_code_key";

CREATE UNIQUE INDEX "Accessories_jobId_key" ON "Accessories"("jobId") WHERE "deletedAt" IS NULL;
CREATE UNIQUE INDEX "Amount_jobId_key" ON "Amount"("jobId") WHERE "deletedAt" IS NULL;
CREATE UNIQUE INDEX "Canopy_jobId_key" ON "Canopy"("jobId") WHERE "deletedAt" IS NULL;
CREATE UNIQUE INDEX "Joint_jobId_key" ON "Joint"("jobId") WHERE "deletedAt" IS NULL;
CREATE UNIQUE INDEX "Load_jobId_key" ON "Load"("jobId") WHERE "deletedAt" IS NULL;
CREATE UNIQUE INDEX "Mezzanine_jobId_key" ON "Mezzanine"("jobId") WHERE "deletedAt" IS NULL;
CREATE UNIQUE INDEX "Quantity_jobId_key" ON "Quantity"("jobId") WHERE "deletedAt" IS NULL;
CREATE UNIQUE INDEX "Quotation_jobId_key" ON "Quotation"("jobId") WHERE "deletedAt" IS NULL;
CREATE UNIQUE INDEX "Roof_jobId_key" ON "Roof"("jobId") WHERE "deletedAt" IS NULL;
CREATE UNIQUE INDEX "Spec_jobId_key" ON "Spec"("jobId") WHERE "deletedAt" IS NULL;
CREATE UNIQUE INDEX "Stair_jobId_key" ON "Stair"("jobId") WHERE "deletedAt" IS NULL;
CREATE UNIQUE INDEX "QuantityPebRoof_quantityId_key" ON "QuantityPebRoof"("quantityId") WHERE "deletedAt" IS NULL;
CREATE UNIQUE INDEX "QuantityCladding_quantityId_key" ON "QuantityCladding"("quantityId") WHERE "deletedAt" IS NULL;
CREATE UNIQUE INDEX "QuantityCanopy_quantityId_key" ON "QuantityCanopy"("quantityId") WHERE "deletedAt" IS NULL;
CREATE UNIQUE INDEX "QuantityAccessories_quantityId_key" ON "QuantityAccessories"("quantityId") WHERE "deletedAt" IS NULL;
CREATE UNIQUE INDEX "QuantityMezzanine_quantityId_key" ON "QuantityMezzanine"("quantityId") WHERE "deletedAt" IS NULL;
CREATE UNIQUE INDEX "QuantityStair_quantityId_key" ON "QuantityStair"("quantityId") WHERE "deletedAt" IS NULL;
CREATE UNIQUE INDEX "QuantityAdditionalBolts_quantityId_key" ON "QuantityAdditionalBolts"("quantityId") WHERE "deletedAt" IS NULL;
CREATE UNIQUE INDEX "Rate_jobId_item_key" ON "Rate"("jobId", "item") WHERE "deletedAt" IS NULL;
CREATE UNIQUE INDEX "CanopyItem_canopyId_code_key" ON "CanopyItem"("canopyId", "code") WHERE "deletedAt" IS NULL;
CREATE UNIQUE INDEX "JointBoltRoof_jointId_roofJointId_key" ON "JointBoltRoof"("jointId", "roofJointId") WHERE "deletedAt" IS NULL;
CREATE UNIQUE INDEX "JointBoltMezzanine_jointId_mezzanineJointId_key" ON "JointBoltMezzanine"("jointId", "mezzanineJointId") WHERE "deletedAt" IS NULL;
CREATE UNIQUE INDEX "FoundationBoltRoof_jointId_foundationJointId_key" ON "FoundationBoltRoof"("jointId", "foundationJointId") WHERE "deletedAt" IS NULL;
CREATE UNIQUE INDEX "MezzanineFloor_mezzanineId_code_key" ON "MezzanineFloor"("mezzanineId", "code") WHERE "deletedAt" IS NULL;
CREATE UNIQUE INDEX "MezzanineFloorExtension_mezzanineId_code_key" ON "MezzanineFloorExtension"("mezzanineId", "code") WHERE "deletedAt" IS NULL;
CREATE UNIQUE INDEX "Sidewall_roofId_side_key" ON "Sidewall"("roofId", "side") WHERE "deletedAt" IS NULL;
CREATE UNIQUE INDEX "SpecProduct_specId_code_key" ON "SpecProduct"("specId", "code") WHERE "deletedAt" IS NULL;
CREATE UNIQUE INDEX "StairItem_stairId_code_key" ON "StairItem"("stairId", "code") WHERE "deletedAt" IS NULL;
