CREATE TYPE "Role" AS ENUM ('SUPER_ADMIN', 'ADMIN', 'ESTIMATOR', 'SALES_COORDINATOR');
ALTER TABLE "User" ADD COLUMN "role" "Role" NOT NULL DEFAULT 'ESTIMATOR';

CREATE TYPE "QuotationStatus" AS ENUM ('DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED');
ALTER TABLE "Quotation" ADD COLUMN "status" "QuotationStatus" NOT NULL DEFAULT 'DRAFT';
ALTER TABLE "Quotation" ADD COLUMN "submittedById" TEXT;
ALTER TABLE "Quotation" ADD COLUMN "submittedAt" TIMESTAMP(3);
ALTER TABLE "Quotation" ADD COLUMN "reviewedById" TEXT;
ALTER TABLE "Quotation" ADD COLUMN "reviewedAt" TIMESTAMP(3);
ALTER TABLE "Quotation" ADD COLUMN "reviewComment" TEXT;
